export const skills = [
  "HTML - semantic & accessible",
  "Responsive Web Design",
  "NPM",
  "Git",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "Styled Components",
  "JavaScript",
  "TypeScript",
  "Immutability",
  "React",
  "React useState, useEffect, useRef",
  "React Hooks",
  "React Router",
  "Redux Saga",
  "Redux (Toolkit)",
  "Error handling",
  "Promises, Async/Await",
  "Working with API (fetch, axios)",
  "SQLite",
  "Teamwork",
  "GitHub Pull Requests & Review",
  "Scrum",
  "Figma",
];

export const nextSkills = [
  "Node.js",
  "Next.js",
  "Three.js",
  "React Native",
  "React Testing Library",
  "WordPress/Drupal",
];
